trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  branches:
    include:
    - main
  always: true

jobs:
  - job: PRChecker
    pool: ubuntu-20.04
    timeoutInMinutes: 60
    steps:
      - checkout: none
      - script: |
          set -ex
          sudo apt-get update && sudo apt-get install -y gh
          echo $TOKEN | gh auth login --with-token
        env:
          TOKEN: $(GH_TOKEN)
        displayName: install dependencies
