trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  branches:
    include:
    - main
  always: true

jobs:
  - job: PRChecker
    pool: ubuntu-20.04
    timeoutInMinutes: 60
    steps:
      - checkout: none
      - script: |
          set -ex
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

          echo $TOKEN | gh auth login --with-token
        env:
          TOKEN: $(GH_TOKEN)
        displayName: install dependencies
