# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

schedules:
- cron: "0 */2 * * *"
  displayName: Hourly build
  branches:
    include:
    - main
  always: true

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: Build
  pool: sonicbld-1es
  jobs:
  - job: Build
    timeoutInMinutes: 120
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo pip3 install azure.core azure.kusto.data azure.kusto.ingest azure.storage.blob azure.storage.queue
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
        # Install Azure cli
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az login --service-principal --use-cert-sn-issuer -u 08fd13c1-63ab-4b08-9007-f4ff86b61248 -p $CERTPATH --tenant 72f988bf-86f1-41af-91ab-2d7cd011db47
      env:
        CERTPATH: $(CERTPATH)
      displayName: Install build tools
    - bash: |
        python3 azure-pipelines/scripts/publish-mssonic-logs.py
      displayName: Ingest data into kusto
