pr: none
trigger: none
schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - mssonicmaster
  always: true
parameters:
- name: branches
  type: string
  default: '202205 202305 202405'
- name: repos
  type: object
  default:
  - sonic-utilities.msft
  - sonic-swss.msft
  - sonic-platform-daemons.msft
  - sonic-platform-common.msft
resources:
  repositories:
  - repository: utilities
    type: github
    name: Azure/sonic-utilities.msft
    endpoint: build
  - repository: swss
    type: github
    name: Azure/sonic-swss.msft
    endpoint: build
  - repository: platform-daemons
    type: github
    name: Azure/sonic-platform-daemons.msft
    endpoint: build
  - repository: platform-common
    type: github
    name: Azure/sonic-platform-common.msft
    endpoint: build
pool: sonic-ubuntu-1c
variables:
  - group: sonicbld
steps:
  - checkout: utilities
    clean: true
  - checkout: swss
    clean: true
  - checkout: platform-daemons
    clean: true
  - checkout: platform-common
    clean: true
  - bash: |
      set -ex
      ls
      cd sonic-utilities.msft
      git remote add head https://github.com/sonic-net/sonic-utilities
      git remote update
      git config pull.rebase false
      cd ../sonic-swss.msft
      git remote add head https://github.com/sonic-net/sonic-swss
      git remote update
      git config pull.rebase false
      cd ../sonic-platform-daemons.msft
      git remote add head https://github.com/sonic-net/sonic-platform-daemons
      git remote update
      git config pull.rebase false
      cd ../sonic-platform-common.msft
      git remote add head https://github.com/sonic-net/sonic-platform-common
      git remote update
      git config --global user.email "sonicbld@microsoft.com"
      git config --global user.name "Sonic Automation"
      git config pull.rebase false
      sudo apt update
      sudo apt install -y gh
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      echo $TOKEN | gh auth login --with-token
      echo $AZURE_DEVOPS_EXT_PAT | az devops login
    env:
      TOKEN: $(GITHUB-TOKEN)
      AZURE_DEVOPS_EXT_PAT: $(MSAZURE-TOKEN)
    displayName: Configure
  - ${{ each repo in parameters.repos }}:
    - bash: |
        set -ex
        cd ${{repo}}
        echo "====${{repo}}===="
        for branch in ${{ parameters.branches }}; do
          echo "    ===$branch==="
          git ls-remote --exit-code origin refs/heads/$branch || { echo "        ==no branch: origin=="; continue; }
          git ls-remote --exit-code head refs/heads/$branch || { echo "        ==no branch: head=="; continue; }
          git branch -D $branch || true
          git checkout -b $branch --track origin/$branch
          git reset HEAD --hard
          git clean -xdff
          git status | grep "^nothing to commit, working tree clean" || { echo "        ==git not clean=="; continue; }
          prehead=$(git log -n 1 --pretty=format:'%H')
          git pull head $branch --no-edit || true
          git status
          if git status | grep "You have unmerged paths";then
            # code conflict, send alert TODO
            continue
            CommitID=$(git log $prehead..HEAD --merge --pretty=format:'%H'  | tail -n 1)
            description="<h1>Please merge $CommitID into ${{repo}}.Do not Cherry-pick!!!</h1>"
            description="code conflict: sonic-net/$(echo ${{repo}} | sed 's/\.msft//'):$branch -> Azure/${{repo}}:$branch<br>"
            description+=$(git log $prehead..HEAD --merge --pretty=format:'%h -%d %s (%cs) [%aN]')
            assign="Gen-Hwa Chiang <gechiang@microsoft.com>"
            # check if the workitem already exist
            az boards work-item update --org https://dev.azure.com/mssonic/ --id $ADO_ID --discussion "$description" -f "Custom Field 1=type_A"
            git merge --abort
            continue
          fi
          head=$(git log -n 1 --pretty=format:'%H')
          if [[ $prehead == $head ]];then
            echo "        ==No change after merging=="
            continue
          fi
          echo "        ==Diff logs=="
          git log $prehead..HEAD --graph --pretty=format:'%h -%d %s (%cs) [%aN]' | xargs -i echo "          {}"
          body=$(git log $prehead..HEAD --graph --pretty=format:'%h -%d %s (%cs) [%aN]')
          body='```<br>'$body'<br>```'
          # push code
          git push https://mssonicbld:$TOKEN@github.com/mssonicbld/${{repo}} HEAD:sonicbld/$branch-merge -f
          # craete PR
          url_=$(gh pr create -R Azure/${{repo}} -H mssonicbld:sonicbld/$branch-merge -B $branch -t "[code sync] Merge code from sonic-net/$(echo ${{repo}} | sed 's/\.msft//'):$branch to $branch" -b "$body" 2>&1; rc=$?)
          url=$(echo "$url_" | grep -Eo https://github.com/Azure/${{repo}}/pull/[0-9]* )
          if echo $url_ | grep "already exists:"; then
            gh pr edit $url -b "$body"
          fi
          sleep 10
          for (( c=1; c<=RETRY_COUNT; c++ ));do
            echo "count: $c"
            sleep 60
            gh pr checks $url | grep https || continue
            gh pr checks $url | grep https | grep pending && continue || break
          done
          gh pr merge $url --merge --admin
        done
      env:
        TOKEN: $(GITHUB-TOKEN)
        AZURE_DEVOPS_EXT_PAT: $(MSAZURE-TOKEN)
      condition: always()
      displayName: '${{repo}} code sync'

