pr: none
trigger: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - main
  always: true

pool:
  vmImage: ubuntu-20.04

parameters:
- name: branches
  type: object
  default:
  - 202205

resources:
  repositories:
  - repository: buildimage
    type: github
    name: Azure/sonic-buildimage-msft
    ref: master
    endpoint: build

steps:
  - checkout: buildimage
    clean: true
    persistCredentials: true
  - bash: |
      set -ex
      git remote add head http://github.com/sonic-net/sonic-buildimage
      git remote update
      git config --global user.email "sonicbld@microsoft.com"
      git config --global user.name "Sonic Automation"
      git config pull.rebase false
      echo $TOKEN | gh auth login --with-token
    env:
      TOKEN: $(GH_PAT)
    displayName: configure
  - ${{each branch in parameters.branches}}:
    - bash: |
        set -ex

        base_branch=${{branch}}
        head_branch=${{branch}}

        git ls-remote --exit-code origin refs/heads/${base_branch} || { echo "Branch missing: sonic-buildimage-msft/${base_branch}"; exit 1; }
        git ls-remote --exit-code head refs/heads/${head_branch} || { echo "Branch missing: sonic-buildimage/${base_branch}"; exit 1; }

        git branch -D ${base_branch} || true
        git checkout -b ${base_branch} --track origin/${base_branch}
        git reset HEAD --hard
        git status | grep "^nothing to commit, working tree clean" || { echo "git reset failed. workspace not clean."; exit 1; }
        git submodule update --init src/sonic-utilities

        prehead=$(git log -n 1 --pretty=format:'%H')

        git pull head ${head_branch} --no-edit || true
        git status
        git submodule

        if ! git status | grep "^nothing to commit, working tree clean";then
          # code conflict
          git reset src/sonic-utilities
          git status | grep "You have unmerged paths" && { echo "both modified not clear."; git merge --abort; exit 1; } || true
          git status
          git submodule
          description=$(git log origin/${base_branch}..HEAD --merge --pretty=format:'%h -%d %s (%cs) [%aN]')
          GIT_EDITOR=true git merge --continue
          assign="Gen-Hwa Chiang <gechiang@microsoft.com>"
          assign="Shilong Liu <shilongliu@microsoft.com>"
          echo "##vso[task.setvariable variable=ASSIGNEDTO]$assign"
          exit 1
        fi

        head=$(git log -n 1 --pretty=format:'%H')
        if [[ $prehead == $head ]];then
          echo "======No change after merging...======"
          exit 0
        fi
        body=$(git log $prehead..HEAD --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cs) %C(bold blue)[%an]%Creset')
        body='```<br>'$body'<br>```'
        git push https://mssonicbld:$TOKEN@github.com/mssonicbld/sonic-buildimage-msft HEAD:codesync-${base_branch} -f
        result=$(gh pr create -R Azure/sonic-buildimage-msft -H mssonicbld:codesync-${base_branch} -B ${base_branch} -t "[code sync] Merge code from sonic-net/sonic-buildimage:${head_branch} to ${base_branch}" -b "$body" 2>&1 || true)
        if echo $result | grep "already exists:"; then
          pr_url=$(echo $result | awk -F"already exists:" '{print$2}')
          gh pr edit $pr_url -b "$body"
        else
          echo $result
          pr_url=$(echo $result | grep "https://github.com/Azure/sonic-buildimage-msft/pull/")
        fi
        gh pr merge --merge --admin -R Azure/sonic-buildimage-msft ${pr_url}
      env:
        TOKEN: $(GH_PAT)
      displayName: ${{branch}} code merge
    - task: CreateWorkItem@1
      inputs:
        workItemType: 'task'
        title: 'code conflict: sonic-net/sonic-buildimage:${{branch}} -> Azure/sonic-buildimage-msft:${{branch}}'
        assignedTo: '$(ASSIGNEDTO)'
        areaPath: '$(ADO_AREA)'
        iterationPath: '$(ADO_ITERATION)'
        fieldMappings: |
          Description=$(DESCRIPTION)
        linkWorkItems: true
        linkType: 'System.LinkTypes.Hierarchy-Reverse'
        linkTarget: 'id'
        targetId: '$(ADO_PARENT)'
      condition: ne(variables.ASSIGNEDTO, '')
      displayName: Create ${{branch}} workitem
