trigger: none
pr: none
schedules:
- cron: "0 0 * * *"
  branches:
    include:
    - main
  always: true
parameters:
  - name: platforms
    type: object
    default:
      - vs
      - centec-arm64
      - marvell-armhf

jobs:
  - job: Build
    pool: sonic-mirror-westus2-2
    timeoutInMinutes: 20
    variables:
      - group: sonicbld
    steps:
      - checkout: self
        clean: true
      - script: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        displayName: install dependencies
      - ${{ each platform in parameters.platforms }}:
        - task: DownloadPipelineArtifact@2
          displayName: Download ${{ platform }} versions-docker file
          inputs:
            source: specific
            project: build
            pipeline: Azure.sonic-buildimage.official.${{ platform }}
            runVersion: 'latestFromBranch'
            runBranch: 'refs/heads/master'
            path: download
            patterns: |
              **/target/versions/default/versions-docker
      - script: |
          set -ex

          echo "$sonicclient" > ~/azpw-kv-1-sonicclient-20240627.pfx.base64
          cat ~/azpw-kv-1-sonicclient-20240627.pfx.base64 | base64 -d > ~/azpw-kv-1-sonicclient-20240627.pfx
          openssl pkcs12 -in ~/azpw-kv-1-sonicclient-20240627.pfx -out ~/client_ssl.pem -clcerts -nodes -password pass:
          az login --service-principal --use-cert-sn-issuer -u 08fd13c1-63ab-4b08-9007-f4ff86b61248 -p ~/client_ssl.pem --tenant 72f988bf-86f1-41af-91ab-2d7cd011db47
          az account set --subscription 90318812-d77d-426d-90a3-44997faf17f4
          images=$(find download -name versions-docker | xargs -i grep -v "==$" {} | awk -F== '{print$1}' | sed -e "s/amd64://" -e "s/arm64://" -e "s/armhf://" | sort -u )
          for i in $images $SYNC_DOCKER_IMAGE_EXTRA
          do
            source=$i
            if [[ "$i" == debian* ]] || [[ "$i" == ubuntu* ]];then
              source=library/$i
            fi
            az acr import -n PublicMirror --source docker.io/$source --image $i --force -u $(user1) -p $(pass1)
          done
        displayName: push image to PublicMirror
        env:
          sonicclient: $(sonicclient)
